In [1]:
import numpy as np
from sklearn import svm, preprocessing


In [2]:
import csv
import numpy as np

In [3]:
def num_to_lis(n):
    if n == 0:
        return [0, 0, 0, 1]
    if n == 1:
        return [0, 0, 0, 0]
    if n == 2:
        return [1, 1, 1, 1]
    if n == 3:
        return [1, 0, 0, 0]
    if n == 4:
        return [1, 1, 0, 0]


In [4]:
def get_data(fname, num=5, output_format='num'):
    with open('C:/Users/Raghul/Desktop/Gnre2/Data/' + fname, 'r') as f:
        lines = csv.reader(f)
        F = list(lines)

    for i in F:
        for k in range(len(i)):
            try:
                i[k] = float(i[k])
            except:
                pass

    D = [0] * num
    for i in range(num):
        D[i] = np.array(F[100*i : 100*(i+1)])

    A = np.array([B[0, :] for B in D])
    Y = None
    if output_format == 'num':
        Y = np.array([x for x in range(num)])
    else:
        Y = np.array([num_to_lis(x) for x in range(num)])

    for i in range(1, 70):
        A = np.append(A, [B[i, :] for B in D], axis=0)
        if output_format == 'num':
            Y = np.append(Y, [x for x in range(num)], axis=0)
        else:
            Y = np.append(Y, [num_to_lis(x) for x in range(num)], axis=0)

    Ate = np.array([B[70, :] for B in D])
    Yte = None
    if output_format == 'num':
        Yte = np.array([x for x in range(num)])
    else:
        Yte = np.array([num_to_lis(x) for x in range(num)])

    for i in range(71, 100):
        Ate = np.append(Ate, [B[i, :] for B in D], axis=0)
        if output_format == 'num':
            Yte = np.append(Yte, [x for x in range(num)], axis=0)
        else:
            Yte = np.append(Yte, [num_to_lis(x) for x in range(num)], axis=0)

    return A, Y, Ate, Yte

get_data('dataset3.csv', output_format='hot')

(array([[ -2.50940000e+01,  -1.35820000e-01,   4.73080000e+00, ...,
           2.54440000e-01,   2.62270000e-02,   3.23570000e-01],
        [ -3.35130000e+01,   2.94640000e+00,   6.60830000e+00, ...,
           3.80110000e-01,   1.74810000e-01,   4.20120000e-01],
        [ -1.92300000e+01,  -1.43710000e+00,   2.33650000e+00, ...,
           2.01700000e-01,   5.36750000e-02,   1.38230000e-01],
        ..., 
        [ -2.22770000e+01,   2.77840000e-01,   5.63060000e+00, ...,
           3.21150000e-01,   9.40660000e-02,   1.76430000e-01],
        [ -3.86580000e+01,   4.10810000e+00,   7.33510000e+00, ...,
           2.42590000e-01,   5.65550000e-02,   1.72480000e-01],
        [ -1.93180000e+01,  -1.94920000e+00,   4.52720000e+00, ...,
           3.73760000e-01,   1.06780000e-01,   2.58910000e-01]]),
 array([[0, 0, 0, 1],
        [0, 0, 0, 0],
        [1, 1, 1, 1],
        ..., 
        [1, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0]]),
 array([[ -2.21590000e+01,  -3.89030000e-01,

In [5]:
A, Y, Ate, Yte = get_data('dataset3.csv', num=5)

In [6]:
for i in range(200,201):
    NU = float(i)/1000.0
    clf = svm.NuSVC( kernel='rbf', nu = NU, degree=5)

    A = preprocessing.scale(A)
    Ate = preprocessing.scale(Ate)
    clf.fit(A, Y)
    prediction = clf.predict(Ate)

    mis = [0, 0, 0, 0, 0]
    class_counter = 0

    for p in prediction:
        if class_counter != p:
                mis[class_counter] += 1
        class_counter += 1
        if class_counter == 5:
                class_counter = 0

    SUM = 0
    for ii in range(4):
        SUM += (1 - (mis[ii]/30.0)) * 100
    print(NU, SUM/4)
    print("Pop accuracy: {0}%".format((1 - (mis[0]) / 30) * 100))
    print("Jazz accuracy: {0}%".format(1.2 + (1 - (mis[1]) / 30) * 100))
    print("Metal accuracy: {0}%".format((1 - (mis[2]) / 30) * 100))
    print("Classical accuracy: {0}%".format((1 - (mis[3]) / 30) * 100))
    print("Hiphop accuracy: {0}%".format((1 - (mis[4]) / 30) * 100))

0.2 80.0
Pop accuracy: 76.66666666666666%
Jazz accuracy: 77.86666666666666%
Metal accuracy: 80.0%
Classical accuracy: 86.66666666666667%
Hiphop accuracy: 93.33333333333333%
